---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data

```{r, echo = TRUE}
library(data.table)
if (!file.exists("activity.zip")) {
    stop("data source file activity.zip missing")
}
DT <- data.table(read.csv(file = "activity.csv", header = TRUE, na.strings = "NA",  stringsAsFactors = FALSE))
DT$datedate <- as.Date(DT$date)
DT$datefactor <- as.factor(DT$date)

```  

## What is mean total number of steps taken per day?


```{r, echo = TRUE}
DF <- data.frame(DT[complete.cases(DT)])
answer <- tapply(DF$steps, DF$datefactor, FUN = function(x) {sum(x, na.rm = TRUE)})
hist(answer, breaks = 100, col = "green")
answer[is.na(answer)] <- 0
mean(answer)
median(answer)
````



## What is the average daily activity pattern?

```{r, echo = TRUE}
answer2 <- aggregate(DF$steps, by = list(DF$interval), FUN = mean)
colnames(answer2) <- c("interval", "mn")
plot(answer2$interval, answer2$mn, type = "l")
answer2[which.max(answer2$mn),]
```


## Imputing missing values


## Are there differences in activity patterns between weekdays and weekends?
